# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a5ef2387f2b6130b1a7f0a585ca6316733c7bd41b510b0b2f74114e8d451d0fccb7376735d6b842fa94a78aa7060006668ecc3d181a1120575b5b52a261378

test:
  secret_key_base: 597707cdbfb1020cafe5c82745681d9ec2f42c6c2c1f1ce02180ee4edfc89fcc269773c6dca79b59f3a0ca78ea49b83daa4a476ec7511e07f3d160ab4b1fc9f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
